  fmod VENDING-MACHINE-SIGNATURE is  
    sorts Coin Item Marking .  
    subsorts Coin Item < Marking .  
    op __ : Marking Marking -> Marking [assoc comm id: null] .  
    op null : -> Marking .  
    op $ : -> Coin [format (r! o)] .  
    op q : -> Coin [format (r! o)] .  
    op a : -> Item [format (b! o)] .  
    op c : -> Item [format (b! o)] .  
  endfm

mod VENDING-MACHINE is  
    including VENDING-MACHINE-SIGNATURE .  
    var M : Marking .  
    rl [add-q] : M => M q .  
    rl [add-$] : M => M $ .  
    rl [buy-c] : $ => c .  
    rl [buy-a] : $ => a q .  
    rl [change] : q q q q => $ .  
  endm


  mod SIMPLE-VENDING-MACHINE is  
    including VENDING-MACHINE-SIGNATURE . 
    var X : Marking . 
    rl [buy-c] : $ => c .  
    rl [buy-a] : $ => a q .  
    rl [change]: q q q q => $ .
    crl [test] : q X => X if $ X => X   
  endm

 search in SIMPLE-VENDING-MACHINE :  
           $ q q q =>! M:Marking .