load relational-sep-logic.maude

mod INDUCTIVE-PREDICATES is 
	protecting INT .
	including HOARE-QUADRUPLE .


	--- Todo : maybe separate InductivePredicates for both Separation and Relational Logic.
	op List(_) : Id -> Relation .

	---var c : Id .
	--- Define the n and a ops
	---ops n a : -> Id .

	---eq List(c) = (((c eqs null) /\ Emp) \/ (exists a . (exists n . (((c |-> a) * ((c + 1) |-> n)) ; (c |-> a) * ((c + 1) |-> n))))) * List(n) [nonexec] .
endm