load separation-logic.maude

fmod HOARE-QUADRUPLE is
	including HOARE-TRIPLE .

	sort HoareQuadruple . 
	--- Relational separation logic condition / predicate - R S
	sort RSLAssertion .

	op _;_ : SLAssertion SLAssertion -> RSLAssertion .

	op {_}_--_{_} : RSLAssertion Code Code RSLAssertion -> HoareQuadruple .

	sort SLHeap .

	op t : -> SLHeap .

	op _*_ : RSLAssertion SLHeap -> RSLAssertion .

endfm 
