parse ((c eqs nil) /\ Emp) \/ (exists a . (exists n . ((c |-> a) * (c + 1 |-> n)
															;
															(c |-> a) * (c + 1 |-> n)))) * List(n) .



reduce getTerm(metaReduce(upModule('PROVER-INTERFACE, false), upTerm(x |-> -) )) .


metaXmatch(upModule('PROVER-INTERFACE, false),  upTerm(x |-> -),  upTerm(x |-> 1),  nil, 0, unbounded, 0) . 


red metaXmatch(upModule('PROVER-INTERFACE, false),  upTerm(x |-> -),  upTerm(x |-> 1),  nil, 0, unbounded, 0) . 
reduce in PROVER-INTERFACE : metaXmatch(upModule('PROVER-INTERFACE, false), upTerm(x |-> -), upTerm(x |->
    1), nil, 0, unbounded, 0) .
rewrites: 6 in 0ms cpu (0ms real) (~ rewrites/second)
result MatchPair: {
	'_:AExp <- 's_['0.Zero],[]}


red metaXmatch(upModule('PROVER-INTERFACE, false),  upTerm((x |-> -) * x |-> -),  upTerm((x |-> 1) * x |-> 1),  nil, 0, unbounded, 0) . 
reduce in PROVER-INTERFACE : metaXmatch(upModule('PROVER-INTERFACE, false), upTerm((x |-> -) * x |-> -),
    upTerm((x |-> 1) * x |-> 1), nil, 0, unbounded, 0) .
rewrites: 6 in 0ms cpu (0ms real) (~ rewrites/second)
result MatchPair: {
	'_:AExp <- 's_['0.Zero],[]}
